name: Auto Deploy Streamlit App to AWS EC2

on:
  push:
    branches:
      - main  # or specify the branch to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Set up SSH key for EC2 access
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: SSH into EC2 and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Pull the latest Docker image from DockerHub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest
          
          # Stop any existing container
          docker stop streamlit-container || true
          docker rm streamlit-container || true
          
          # Run the new container
          docker run -d -p 8501:8501 --name streamlit-container ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest
        EOF
